### ISSUE TITLE
Provide Windows wheels

### ISSUE THREAD

**Issue by pfmoore** [coady/placeholder#6]
Now that the project needs to be built with a C compiler, would you consider shipping Windows wheels? Not all Windows systems have a C compiler available.

**Comment by coady** [comment]
It's not convenient for me to test on windows, but GitHub built it, so wheels are included in v1.2.1. Thanks.

**Comment by pfmoore** [comment]
Much appreciated. If it's simply a matter of getting the test suite to run in github actions, let me know and I'd be happy to try to sort that out.
