### ISSUE TITLE
 Plugging the `_.foo.func` hole?

### ISSUE THREAD

**Issue by mentalisttraceur** [coady/placeholder#8]
So the fact that `_.foo.{{ bar }}` always creates a callable which does the equivalent of `lambda x: x.foo.{{ bar }}`, _unless_ `{{ bar }}` is one special-cased string, in which case it returns `operator.attrgetter('foo')`, is something I would call a "hole" - in the regular space of the interface, there's this one spot which you have to know about, remember, and remain vigilant about.

When some library gets enough users, most users don't look at the docs, they just learn and generalize from example. It's very easy for a developer to end up seeing at least one `_.foo.bar` example and naturally assume regularlity of interface, only to one day accidentally fall into this hole when `_.foo` happens to be, say, something like a  `functools.partial` instance - something with a `.func` attribute.

So here's the question: for the next backwards-compatibility-breaking release, are you willing to consider alternatives for getting the raw underlying function, which don't require poking a hole in the surface of the interface?

For example, perhaps an extra external function, so that you'd do `from placeholder import raw_callable` or whatever you want to call it, and then instead of `_.foo.func` we'd do `raw_callable(_.foo)`?

**Comment by coady** [comment]
Yeah, in fact there's a cleaner interface already: the registered functions are iterable. So `.func` isn't needed anymore. Since it's documented it'll have to be deprecated first though.
